#
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
#
version: '3.8'
services:
    pushgateway:
        container_name: pushgateway
        network_mode: host
        pid: host
        restart: unless-stopped
        image: prom/pushgateway
    prometheus:
        container_name: prometheus
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/home/$cfn_cluster_user/aws-parallelcluster-monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
            - 'prometheus-data:/prometheus'
        image: prom/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--web.external-url=/prometheus/'
            - '--web.route-prefix=/'
    grafana:
        container_name: grafana
        network_mode: host
        pid: host
        restart: unless-stopped
        environment:
            - 'GF_SECURITY_ADMIN_PASSWORD=Grafana4PC!'
            - 'GF_SERVER_ROOT_URL=http://%(domain)s/grafana/'
        volumes:
            - '/home/$cfn_cluster_user/aws-parallelcluster-monitoring/grafana:/etc/grafana/provisioning'
            - 'grafana-data:/var/lib/grafana'
        image: grafana/grafana
    prometheus-node-exporter:
        container_name: node-exporter
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
        image: quay.io/prometheus/node-exporter
        command:
            - '--path.rootfs=/host'
    nginx:
        container_name: nginx
        network_mode: host
        pid: host
        #ports:
        #    - 80:80
        #    - 443:443
        restart: unless-stopped
        depends_on:
            submit_ui:
                condition: service_started
        volumes:
            - '/home/$cfn_cluster_user/aws-parallelcluster-monitoring/nginx/conf.d:/etc/nginx/conf.d/'
            - '/home/$cfn_cluster_user/aws-parallelcluster-monitoring/nginx/ssl:/etc/ssl/'
            - '/home/$cfn_cluster_user/aws-parallelcluster-monitoring/www:/usr/share/nginx/html'
            - 'nodejs-build:/usr/share/nginx/html/runsubmit'
        image: nginx
    submit_ui:
        container_name: submit_ui
        build:
            context: ../submit_ui
            dockerfile: Dockerfile
        volumes:
            - 'nodejs-build:/usr/src/app/build'
    submit_backend:
        restart: always
        container_name: submit_backend
        network_mode: host
        pid: host
        build:
            context: ../submit_backend
            dockerfile: Dockerfile
        expose:
            - 5000
        volumes:
            - '../submit_backend:/usr/src/app'
        environment:
            - FLASK_ENV=development
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
volumes:
    prometheus-data:
    grafana-data:
    nodejs-build:

